### ISSUE TITLE
process blocking itself

### ISSUE THREAD

**Issue by lukexue** [markwellis/net-amqp-rabbitmq#16]
perl 5.14.2  (net-amqp-rabbitmq 0.005007)

"Sometime" ,the program will block even have new message income (maybe cause by ack?)

while(1){
$rv = $mq->recv();
$mq->ack( 1, $k );
}

$mq->get() not work 
The message will be deleted , but $rv is null
while(1){
$rv = $mq->get(1,$gname);
print $rv;
}

---
The heartbert option(at connection) will solve the problem.

**Comment by manchicken** [comment]
@lukexue, If you're still able to replicate this, please let me know. I haven't been able to replicate this yet, and nobody is able to replicate this then I think we should close this issue.

**Comment by lukexue** [comment]
ok,  just close it. 
thanks
