### ISSUE TITLE
Detach this fork from the parent repo

### ISSUE THREAD

**Issue by autarch** [markwellis/net-amqp-rabbitmq#31]
It doesn't make that much sense to show the link back to Net::RabbitMQ, as this really isn't a fork in any meaningful sense (it might've started that way, but it appears to be its own thing now).

I think @markwellis has to contact GitHub support to make that happen. See the bottom of https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/ for reference.

**Comment by markwellis** [comment]
that makes sense, i'll do that. @autarch++

**Comment by markwellis** [comment]
this has been done
