### ISSUE TITLE
When supplying an x-dead-letter-exchange argument while declaring a queue, we run into a problem where RabbitMQ chokes on the type.

### ISSUE THREAD

**Issue by manchicken** [markwellis/net-amqp-rabbitmq#41]
RabbitMQ wants the x-dead-letter-exchange argument and the x-dead-letter-routing-key to be UTF-8, not BYTES. Currently, this is broken functionality, preventing you from declaring a queue with these fields.

**Comment by manchicken** [comment]
Pull request #36 is where this issue originated, they were awesome and gave us a test to use as well.

**Comment by manchicken** [comment]
Hey everybody, I'm about to submit a pull request for this: https://github.com/manchicken/net-amqp-rabbitmq/commit/3273a77badbcd18aaccf03e2e48274ec021ab9b5

I'm currently waiting until it builds okay in Travis, and then I'll submit the pull request.

**Comment by alnewkirk** [comment]
Thanks @manchicken.
