### ISSUE TITLE
[Solution proposed] Growing memory usage after publish

### ISSUE THREAD

**Issue by DavsX** [markwellis/net-amqp-rabbitmq#63]
Hi! I've found a nasty memory leak, which happens on publish, if in the last argument (props hash) we have headers defined.

A sample/simple script can be found below. The leaking can be stopped by commenting out the `headers => {}` hash. The leaking can be seen with for example `htop`. My attempts to find the cause of this were unsuccessful. Also turning on DEBUG in `RabbitMQ.xs` and publishing something with the `headers` hash set in the `props` hash results in segfault.

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Net::AMQP::RabbitMQ;

my $exchange = "test_queue";
my $queue = "test_queue";

my $mq = Net::AMQP::RabbitMQ->new();
$mq->connect("localhost", {
    user => 'guest',
    password => 'guest',
    port => '5672',
    vhost => '/',
}) or die "connect $!";

$mq->channel_open(1);
$mq->purge(1, $queue);

for (1..500000) {
    $mq->publish(1, "", "Test data", { exchange => $exchange }, {
        headers => {
			leakMe => "Hello World, I'm leaking!",
        },
    });
}

$mq->purge(1, $queue);
```

**Comment by markwellis** [comment]
interesting, i'll look at this tonight

**Comment by DavsX** [comment]
here is the output of my `perl -V` : http://pastebin.com/nry5StSz

**Comment by DavsX** [comment]
My C knowledge is limited, but I found something that smells fishy. Here https://github.com/markwellis/net-amqp-rabbitmq/blob/master/RabbitMQ.xs#L802 we allocate memory from the hash_pool for our headers hash but as far as I see it is not emptied.

**Comment by DavsX** [comment]
Also is here https://github.com/markwellis/net-amqp-rabbitmq/blob/master/RabbitMQ.xs#L927 a typo? Shouldn't we init the `hash_pool` then the `array_pool`? (hash pool is initialized twice!)

**Comment by manchicken** [comment]
The second one looks fishy, the first one doesn't look weird at first
glance.

Can you give us the metrics of the memory leak?

We should probably try to reproduce this in pure C so that we can stick a
profiler onto it.

**Comment by DavsX** [comment]
The metrics of the leak? I was looking at htop for the `RES` column. Would you like to find out how fast the memory is growing? That entirely depends of the size of the `headers` hash content and the rate which I'm sending data, so the number is not universal.

**Comment by manchicken** [comment]
If the growth is at the same rate as the growth of the headers content,
that doesn't really sound like a leak to me.

**Comment by markwellis** [comment]
It does to me, if memory for the headers is being allocated but never
freed, it makes sense that it would grow at the same rate as the header
contents

**Comment by DavsX** [comment]
I already renamed the issue to Growing memory. The issue is, that the hash_pool memory pool is atm cleaned only on connect/DESTROY. With the current state of the code I'd have to periodically destroy and recreate my Net::AMQP::RabbitMQ object, so the memory would not grow out of bounds. 

I had reports from a daemon running in production growing 1-2GB in RAM during a weekend (don't have any more details about it, but at this stage it makes the module not production ready)

**Comment by DavsX** [comment]
With version 1.0 the memory growth is resolved! Great job!

**Comment by markwellis** [comment]
No problem! :)

**Comment by manchicken** [comment]
Yay!
